version: '3.1'

services:
  db:
    image: postgres:16.2
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD?Variable not set}
      POSTGRES_USER: ${POSTGRES_USER?Variable not set}
      POSTGRES_DB: ${POSTGRES_DB?Variable not set}
    ports:
      - ${POSTGRES_PORT?Variable not set}:5432
